all_venue_dict = {
  '&nbsp;Druid Hill Park':'Druid Hill Park',
  '&nbsp;Free Farm':'Free Farm',
  '&nbsp;Ottobar':'Ottobar',
  '&nbsp;Roland Water Tower (4210 Roland Ave)':'Roland Water Tower',
  '1 E Baltimore St':'1 E Baltimore St',
  '1 E. Baltimore St':'1 E Baltimore St',
  '101 E Pratt St':'101 E Pratt St',
  '1100 Hollins St':'1100 Hollins St',
  '1100 Hollins St.':'1100 Hollins St',
  '1117 E 36th St':'1117 E 36th St',
  '1118 Hollins St':'1118 Hollins St',
  '1128 Hollins St.':'1128 Hollins St.',
  '1217 E Preston St':'1217 E Preston St',
  '1217 E. Preston St':'1217 E Preston St',
  '13.5 Wine Bar':'13.5 Wine Bar',
  '1300 Bayard St':'1300 Bayard St',
  '1420 Eutaw St':'1420 Eutaw St',
  '1423 John St':'1423 John St',
  '1443 Riverside Ave':'1443 Riverside Ave',
  '1500 McCulloh St':'1500 McCulloh St',
  '1500 Mcculloh St':'1500 McCulloh St',
  '1505 Eutaw PL':'1505 Eutaw Pl',
  '1505 Eutaw Pl':'1505 Eutaw Pl',
  '1601 Ridgely St':'Lost and Found',
  '1601 Ridgely St.':'Lost and Found',
  '1611 Guilford Ave':'Guilford Hall Brewery',
  '1616 Thame St':'Sound Garden',
  '1616 Thames St':'Sound Garden',
  '1627 E Fort Ave':'1627 E Fort Ave',
  '1701 N Charles St':'1701 N Charles St',
  '1701 N Charles St./Crown/Rituals/Annex Lounge':'1701 N Charles St',
  '1701 N. Charles St./Crown/Rituals/Annex Lounge':'1701 N Charles St',
  '1709 N Charles St':'1709 N Charles St',
  '1750 Union Ave':'1750 Union Ave',
  '1801 Bar':'1801 Bar',
  '1801 St Paul St':'1801 St Paul St',
  '1810 Webster St':'1810 Webster St',
  '1828 Webster St':'1828 Webster St',
  '1901 N Charles St':'1901 N Charles St',
  '1915 Maryland Ave':'1915 Maryland Ave',
  '1915 Maryland Avenue':'1915 Maryland Ave',
  '1919':'1919',
  '1919 Fleet St':'1919',
  '200 Block of Read St':'200 Read St',
  '200 Block of Read St.':'200 Read St',
  '200 Read St':'200 Read St',
  '200 St Paul Pl':'200 St Paul Pl',
  '200 St Paul Place':'200 St Paul Pl',
  '200 St. Paul Place':'200 St Paul Pl',
  '2010 Clipper Park Rd Suite 105':'2010 Clipper Park Rd Suite 105',
  '202 Ingleside Ave':'The Vortex',
  '21 W. Mt Royal 5th Floor':'University of Baltimore Student Center Auditorium',
  '2100 Liberty Heights':'2100 Liberty Heights',
  '218 W Saratoga St':'218 W Saratoga St',
  '218 West Saratoga St':'218 W Saratoga St',
  '2200 Eutaw St':'2200 Eutaw St',
  '2200 Eutaw St.':'2200 Eutaw St',
  '2225 Hargrove St':'The Hargrove',
  '225 Holliday St':'The Peale',
  '2401 N Rose St':'2401 N Rose St',
  '2401 N. Rose St':'2401 N Rose St',
  '2401 N. Rose St.':'2401 N Rose St',
  '2407 Ken Oak Road':'2407 Ken Oak Road',
  '2410 Erdman Ave':'2410 Erdman Ave',
  '2412 College Ave':'2412 College Ave',
  '25 E. Cross St':'P.A.L.M.',
  '2610 St Paul St':'2610 St Paul St',
  '2613 Talbot Rd':'2613 Talbot Rd',
  '2640 Space':'2640 Space',
  '26th and Guilford':'26th and Guilford',
  '27 S Patterson Park':'27 S Patterson Park',
  '2701 Sisson St':'Sisson Street Community Park',
  '2703 Halcyon Ave':'2703 Halcyon Ave',
  '2741 Guilford Ave':'2741 Guilford Ave',
  '2741 Guilford Ave.':'2741 Guilford Ave',
  '2801 N Calvert St':'2801 N Calvert St',
  '2925 Heswick Rd':'2925 Heswick Rd',
  '2999 Boston St':'2999 Boston St',
  '29th St &amp; Charles St':'29th St and Charles St',
  '29th St and Charles St':'29th St and Charles St',
  '30 W North Ave':'30 W North Ave',
  '30 West North Ave':'30 W North Ave',
  '30 West North Ave.':'30 W North Ave',
  '300 W Pratt St':'Phlote',
  '300 W. Pratt St.':'Phlote',
  '300 West Pratt St':'Phlote',
  '3000 Abell Ave':'3000 Abell Ave',
  '3000 Block of Abell Ave.':'3000 Abell Ave',
  '3000 Falls Rd':'The Wiggle Room',
  '3001 East Dr':'3001 East Dr',
  '3001 East Dr.':'3001 East Dr',
  '301 McMechen St':'301 McMechen St',
  '307 Northway':'307 Northway',
  '3126 Weaver Ave':'3126 Weaver Ave',
  '3137 Eastern Ave. Baltimore':'3137 Eastern Ave. Baltimore',
  '3209 Rosalie Ave':'3209 Rosalie Ave',
  '321 E. 28th St':'321 E. 28th St',
  '322 W Baltimore St.':'MAP Technologies',
  '322 W. Baltimore St.':'MAP Technologies',
  '32nd St &amp; Brentwood':'32nd St and Brentwood',
  '32nd St &amp; Brentwood Ave':'32nd St and Brentwood',
  '32nd St &amp; Brentwood Ave.':'32nd St and Brentwood',
  '32nd St and Brentwood':'32nd St and Brentwood',
  '32nd St. &amp; Brentwood Ave':'32nd St and Brentwood',
  '3300 Clipper Mill Rd':'3300 Clipper Mill Rd',
  '3301 Waterview Ave':'Middle Branch Park',
  '3308 Glenmore Ave':'3308 Glenmore Ave',
  '3311 Ailsa Ave':'3311 Ailsa Ave',
  '3355 Keswick':'3355 Keswick Rd',
  '3355 Keswick Rd':'3355 Keswick Rd',
  '3510 Ash St':'3510 Ash St',
  '3531 Chestnut Ave':'3531 Chestnut Ave',
  '3531 Chestnut Ave. (outdoors)':'3531 Chestnut Ave',
  '3539 Clipper Mill Rd':'3539 Clipper Mill Rd',
  '3539 Clipper Mills Rd':'3539 Clipper Mill Rd',
  '4 q u a r i u m':'4 q u a r i u m',
  '4000 Buena Vista Ave':'4000 Buena Vista Ave',
  '4001 Harford Rd':'4001 Harford Rd',
  '406 N. Howard St':'406 N. Howard St',
  '4127 Westview Rd':'4127 Westview Rd',
  '4303 Maine Ave':'4303 Maine Ave',
  '431 Notre Dome Lane':'431 Notre Dome Lane',
  '4500 Harford Rd':'4500 Harford Rd',
  '4500 Harford Rd (outdoors)':'4500 Harford Rd',
  '4500 Harford Road':'4500 Harford Rd',
  '4518 Raspe Ave':'4518 Raspe Ave',
  '4QUARIAM':'4 q u a r i u m',
  '4quarium':'4 q u a r i u m',
  '4quarium (DM bands for address)':'4 q u a r i u m',
  '709 Howard St':'NoMuNoMu',
  '709 N. Howard St':'NoMuNoMu',
  '709 N. Howard St.':'NoMuNoMu',
  '811 Cathedral St':'Emmanuel Episcopal Church',
  '911 S Ann St':'911 S Ann St',
  '<span style="color: #444444">Fadensonnen</span>':'Fadensonnen',
  'Address sent after ticket purchase on RA':'No address listed',
  'Address shown after ticket purchase (zip 21210)':'No address listed',
  'Aquarium':'4 q u a r i u m',
  'Baby’s On Fire (Fells Point)':'Sound Garden',
  'Baby’s on Fire (Fells Point)':'Sound Garden',
  'Baby’s on Fire - Fells Point':'Sound Garden',
  'Baltimore Free Farm':'Free Farm',
  'Bar 1801':'1801 Bar',
  'Barclay &amp; 30th St + Peabody Heights Brewery':'Peabody Heights Brewery',
  'Bogus Gallery':'Bogus Gallery',
  'Call 877-577-BOOM or DM Crass Lips Records':'No address listed, DM for address',
  'Central Library (400 Cathedral St)':'Enoch Pratt Central Library',
  'Charles St. between North Ave. and 23rd St.':'1901 N Charles St',
  'Charles Village (message bands for address)':'No address listed, DM for address',
  'City of Gods':'1118 Hollins St',
  'DM @andieisonline for tix/address':'No address listed, DM for address',
  'DM @beatitude.bmore for address':'No address listed, DM for address',
  'DM @sidebarbaltimore for address':'No address listed, DM for address',
  'DM Darkroom for address':'No address listed, DM for address',
  'DM defeatofcivilization for address':'No address listed, DM for address',
  'DM Digital Xscape for address':'No address listed, DM for address',
  'DM Nothing Nice':'No address listed, DM for address',
  'DM Signal Route for address':'No address listed, DM for address',
  'DM artists for address':'No address listed, DM for address',
  'DM bands for address':'No address listed, DM for address',
  'DM beatitude.bmore for address':'No address listed, DM for address',
  'DM data_mine on Instagram for address':'No address listed, DM for address',
  'DM digitalxscape for address':'No address listed, DM for address',
  'DM everafter__party for address':'No address listed, DM for address',
  'DM inmysoulzine for address':'No address listed, DM for address',
  'DM itsjacqjill for address':'No address listed, DM for address',
  'De Kleine Duivel':'De Kleine Duivel',
  'Dear Globe Coffeebar':'Dear Globe Coffeebar',
  'Design Distillery':'Design Distillery',
  'Design Distillery (1414 Key Hwy)':'Design Distillery',
  'Design Distillery (21414 Key Hwy)':'Design Distillery',
  'Dick’s Halfway Inn':'Dick’s Halfway Inn',
  'Digital Xscape':'Digital Xscape',
  'Digital Xscape (DM digitalxscape for address)':'Digital Xscape',
  'Digital Xscape (DM for Address)':'Digital Xscape',
  'Disconsin':'Disconsin',
  'Disconsin (DM bands for address)':'Disconsin',
  'Disconsin (message artists for address)':'Disconsin',
  'Disconsin (message bands for address)':'Disconsin',
  'Dog House Mansion':'Dog House Mansion',
  'Dog House Mansion (5607 Roland Ave)':'Dog House Mansion',
  'Don’t Know Tavern':'Don’t Know Tavern',
  'Douglas Memorial Church':'Douglas Memorial Church',
  'Douglas Memorial Community Church':'Douglas Memorial Church',
  'Dream Mega Lounge':'Dream Mega Lounge',
  'Dream Mega Lounge (10 S. Calvert St.)':'Dream Mega Lounge',
  'Druid Hill Park':'Druid Hill Park',
  'Druid Hill Park Pool':'Druid Hill Park',
  'Ekiben Hampden':'Ekiben Hampden',
  'El Bufalo':'El Bufalo',
  'Email hello@respektmusic.com':'No address listed, DM for address',
  'Ema’s Corner':'Ema’s Corner',
  'Ema’s Corner':'Joe Squared',
  'Ema’s Corner (33 W North Ave)':'Ema’s Corner',
  'Emmanuel Episcopal Church':'Emmanuel Episcopal Church',
  'Enigma Bar':'Enigma Bar',
  'Enoch Pratt Central Library':'Enoch Pratt Central Library',
  'Enoch Pratt Central Library (400 Cathedral St)':'Enoch Pratt Central Library',
  'Eubie Blake Cultural Center':'Eubie Blake Cultural Center',
  'Euphoria':'Euphoria',
  'Faddensonnen':'Fadensonnen',
  'Fadensonnen':'Fadensonnen',
  'Fadensonnen   <br />':'Fadensonnen',
  'Fadensonnen (3 W 23rd St.)':'Fadensonnen',
  'Fadensonnen Beer Garden':'Fadensonnen',
  'Fadensonnen Upstairs Wine Bar':'Fadensonnen',
  'Fadensonnen Wine Bar':'Fadensonnen',
  'Fadensonnen Wine Bar Upstairs':'Fadensonnen',
  'Fadensonnen Winebar':'Fadensonnen',
  'Fells Point':'Fells Point',
  'Fell’s Point':'Fells Point',
  'Floristree':'Floristree',
  'Flower Tower':'Flower Tower',
  'Fort Armistead':'Fort Armistead',
  'Fort Armistead (DM bands for address)':'Fort Armistead',
  'Fort Harmistead (DM bands for address)':'Fort Armistead',
  'Franklin Square Park':'Franklin Square Park',
  'Frank’s Bay Tavern':'Frank’s Bay Tavern',
  'Free Farm':'Free Farm',
  'Free Farm (3511 Ash St)':'Free Farm',
  'Freight Zone':'Freight Zone',
  'Freight Zone (next to True Vine)':'Freight Zone',
  'Frog Shack':'Frog Shack',
  'Frog Shack (DM @zd_rom_ for address)':'Frog Shack',
  'Function Coworking Community':'Function Coworking Community',
  'George Peabody Library':'George Peabody Library',
  'Get Shredded Vintage':'Get Shredded Vintage',
  'Golden West':'Golden West',
  'Golden West Cafe':'Golden West',
  'Good Neighbor Design Garage':'Good Neighbor Design Garage',
  'Goucher College':'Goucher College',
  'Goucher College (Heubeck Multipurpose Room)':'Goucher College',
  'Goucher College (Trustees Hall)':'Goucher College',
  'Goucher College Chapel':'Goucher College',
  'Goucher Glass Studio Trustees Hall':'Goucher College',
  'Graffiti Warehouse':'Graffiti Warehouse',
  'Grass Bmore':'Grass Bmore',
  'Grass Bmore (1100 Wilcomico St, Suite 350)':'Grass Bmore',
  'Greektown Square &amp; Event Center':'Greektown Square and Event Center',
  'Greektown Square and Event Center':'Greektown Square and Event Center',
  'Greektown square and event center':'Greektown Square and Event Center',
  'Guilford Hall Brewery':'Guilford Hall Brewery',
  'HI Baltimore Hostel':'HI Baltimore Hostel',
  'Hammerjacks':'Hammerjacks',
  'Hampden':'Hampden',
  'Hampden Park':'Hampden Park',
  'Hampden Park (Outdoors)':'Hampden Park',
  'Hampden Skate Park':'Hampden Skate Park',
  'Hampden Skatepark':'Hampden Skate Park',
  'Hard Rock Cafe':'Hard Rock Cafe',
  'Hard Rock Cafe (601 E Pratt St)':'Hard Rock Cafe',
  'Hargrove':'Hargrove',
  'Haus':'Haus',
  'Haus (DM wmbc_radio for address)':'Haus',
  'Heinz Park':'Heinz Park',
  'Herring Run':'Herring Run',
  'Herring Run Park':'Herring Run',
  'Herring Park Run (Hall Springs Area)':'Herring Run',
  'Hidden Harvest':'Hidden Harvest',
  'Hidden Harvest Community Farm (1825 N Calvert St)':'Hidden Harvest',
  'Hippodrome':'Hippodrome',
  'Hippodrome&nbsp;':'Hippodrome',
  'Hollins Market':'Hollins Market',
  'Holy Frijoles':'Holy Frijoles',
  'Holy Frijoles &nbsp;':'Holy Frijoles',
  'Holy Frijoles Upstairs':'Holy Frijoles',
  'Holy Frijoles</strike>':'Holy Frijoles',
  'Holy Frjoles':'Holy Frijoles',
  'Homewood Friends Meeting House':'Homewood Friends Meeting House',
  'Homewood Friends Meeting House (3107 N. Charles St.)':'Homewood Friends Meeting House',
  'Hot Dog Central':'Hot Dog Central',
  'Hot Rock Art Collective':'Hot Rock Art Collective',
  'Hot Rock Art Collective (3701 Parkside Dr.)':'Hot Rock Art Collective',
  'Houde of Chiefs':'House of Chiefs',
  'House of Chiefs':'House of Chiefs',
  'House of Chiefs (4603 York Road)':'House of Chiefs',
  'House of Chiefs (4604 York Rd)':'House of Chiefs',
  'House of Sedulo':'House of Sedulo',
  'House of Za':'House of Za',
  'House of Za (DM bands for address)':'House of Za',
  'House show (DM bands for address)':'No address listed, DM for address',
  'Hoy Frijoles':'Holy Frijoles',
  'Idle Hour':'Idle Hour',
  'Idle Hour (201 E Fort Ave)':'Idle Hour',
  'Iiinteruption Studios':'Iiinteruption Studios',
  'Immaculate Heart of Mary Church':'Immaculate Heart of Mary Church',
  'Inner Habor Amphitheater':'Inner Habor Amphitheater',
  'Inner Harbor Amphitheater':'Inner Habor Amphitheater',
  'Inner Harbor Wine Village':'Inner Harbor Wine Village',
  'Jacksons House':'Jacksons House',
  'James E Hooper House':'James E Hooper House',
  'James E Hooper House (100 east 23rd St)':'James E Hooper House',
  'Jewish Museum of Maryland':'Jewish Museum of Maryland',
  'Joe Squared':'Joe Squared',
  'Joe Squared Upstairs':'Joe Squared',
  'Joe Squared&nbsp;':'Joe Squared',
  'Joe Squared&nbsp;Electric Feels. 9PM, $17 @ Rams Head':'Joe Squared',
  'Joe SquaredSpite, Boundaries, Vatican, Bodybox, Delenda. 6PM, $19 @ Soundstage':'Joe Squared',
  'Joes Tavern':'Joes Tavern',
  'Joes Tavern (1006 Dundalk Ave)':'Joes Tavern',
  'Johns Hopkins University':'Johns Hopkins University',
  'Johns Hopkins University (Shriver Hall Auditorium)':'Johns Hopkins University',
  'Kenwood Tavern':'Kenwood Tavern',
  'Keystone Korner':'Keystone Korner',
  'Koopatini Haus (DM bands for address)':'Koopatini House',
  'Koopatini House':'Koopatini House',
  'Ladew Topiary Gardens':'Ladew Topiary Gardens',
  'Lake Montebello':'Lake Montebello',
  'Lansdowne Skatepark':'Lansdowne Skatepark',
  'Laurens &amp; Roberts St':'Laurens and Roberts St',
  'Laurens and Roberts St':'Laurens and Roberts St',
  'Le Mondo':'Le Mondo',
  'Le Mondo (406 N Howard)':'Le Mondo',
  'Lewis Museum':'Lewis Museum',
  'Lith Hall':'Lithuanian Hall',
  'Lithuanian Hall':'Lithuanian Hall',
  'Little Havana':'Little Havana',
  'Local Oyster (Locust Point)':'Local Oyster (Locust Point)',
  'Locals Only':'P.A.L.M.',
  'Location TBA':'No address listed',
  'Lost &amp; Found (1601 Ridgely St)':'Lost and Found',
  'Lost &amp; Found (1601 Ridgely St.)':'Lost and Found',
  'Lost and Found':'Lost and Found',
  'Lovely Lane Church':'Lovely Lane Church',
  'Luna Garden (1616 Thames St)':'Sound Garden',
  'Lwn Sphere (4518 Raspe Ave)':'4518 Raspe Ave',
  'Lwnsphere (4518 Raspe Ave)':'4518 Raspe Ave',
  'M&T Bank Exchange':'M&T Bank Exchange',
  'M&amp;T Bank Exchange':'M&T Bank Exchange',
  'M.A.P. Technologies':'MAP Technologies',
  'M.A.P. Technologies (322 W Baltimore St.)':'MAP Technologies',
  'M.A.P. Technologies (322 W. Baltimore St)':'MAP Technologies',
  'MAP Technologies':'MAP Technologies',
  'MECU Pavilion':'Pier Six',
  'MICA Game Lab':'MICA Game Lab',
  'MICA Game Lab (100 Dolphin St)':'MICA Game Lab',
  'MICA Meyerhoff Gallery':'MICA Meyerhoff Gallery',
  'Madison &amp; Presstman St':'Madison and Presstman St',
  'Madison and Presstman St':'Madison and Presstman St',
  'Manor Mill':'Manor Mill',
  'Map Technologies (322 W. Baltimore St)':'MAP Technologies',
  'Map Technologies (322 W. Baltimore St.)':'MAP Technologies',
  'MapTech Games':'MAP Technologies',
  'Marikle Chapel':'Marikle Chapel',
  'Marikle Chapel (Notre Dame of Maryland University, Theresa Hall)':'Marikle Chapel',
  'Market Maven':'Market Maven',
  'Maryland Science Center':'Maryland Science Center',
  'Maximon':'Maximon',
  'Mercury Theater':'Mercury Theater',
  'Mercury Theatre':'Mercury Theater',
  'Metro':'Metro Gallery',
  'Metro Gallery':'Metro Gallery',
  'Metro GalleryB&bull;A&bull;D Night | Gunbuster. 6PM, $FREE @ Crown':'Metro Gallery',
  'Mi Comalito':'Mi Comalito',
  'Mi Comalito (2101 N Charles St)':'Mi Comalito',
  'Mice In The Attic':'Mice in the Attic',
  'Mice in the Attic':'Mice in the Attic',
  'Mickey’s Joint':'Micky’s Joint',
  'Mickey’s Joint (5403 Harford Rd)':'Micky’s Joint',
  'Micky’s Joint':'Micky’s Joint',
  'Middle Branch Park':'Middle Branch Park',
  'Middle Branch Park (3301 Waterview Ave)':'Middle Branch Park',
  'Mindpub':'Mindpub',
  'Ministry of Brewing':'Ministry of Brewing',
  'Mobtown (4015 Foster Ave)':'Mobtown Brewing',
  'Mobtown Ballroom':'Mobtown Ballroom',
  'Mobtown Ballroom &amp; Club Car &amp; Royal Blue &amp; Night Owl':'Mobtown Ballroom',
  'Mobtown Brewery':'Mobtown Brewing',
  'Mobtown Brewing':'Mobtown Brewing',
  'Mobtown Brewing Co.':'Mobtown Brewing',
  'Modell Lyric':'The Lyric',
  'Montebello Terrace (4500 Harford Road)':'4500 Harford Rd',
  'Monument Brewing':'Monument Brewing',
  'Monument City Brewing':'Monument Brewing',
  'Monument City Brewing</strike>':'Monument Brewing',
  'Morsbergers':'Morsbergers',
  'Morsberger’s':'Morsbergers',
  'Morsebegers':'Morsbergers',
  'Mosaic':'Mosaic',
  'Mothers Grille':'Mothers Grille',
  'Mother’s':'Mothers Grille',
  'Motor House':'Motor House',
  'Motorhouse':'Motor House',
  'Mount Royal Soap Co.':'Mount Royal Soap Co.',
  'Mt Vernon':'Mt Vernon',
  'Mt Vernon Marketplace':'Mt Vernon Marketplace',
  'Mt Vernon Records':'Mt Vernon Records',
  'Mt. Royal Soaps':'Mount Royal Soap Co.',
  'Mt. Vernon':'Mt Vernon',
  'Mulberry St and Park Ave':'Mulberry St and Park Ave',
  'Mums':'Mums',
  'N. Charles St &amp; 29th St':'29th St and Charles St',
  'National Aquarium':'National Aquarium',
  'Nevermore Hall':'Nevermore Hall',
  'Night Owl Gallery':'Night Owl Gallery',
  'No Land Beyond':'No Land Beyond',
  'No Land Beyond, 2125 Maryland Ave (new location)':'No Land Beyond',
  'No address listed':'No address listed',
  'No address listed, DM for address':'No address listed, DM for address',
  'NoMu NoMu':'NoMuNoMu',
  'NoMu NoMu (709 N. Howard St)':'NoMuNoMu',
  'NoMuNoMu':'NoMuNoMu',
  'NoMüNoMü':'NoMuNoMu',
  'Nobles Bar &amp; Grill':'Nobles Bar and Grill',
  'Nobles Bar and Grill':'Nobles Bar and Grill',
  'Normal&rsquo;s Books':'Normal’s Books',
  'Normals':'Normal’s Books',
  'Normals Books':'Normal’s Books',
  'Normal’s':'Normal’s Books',
  'Normal’s Books':'Normal’s Books',
  'North Ave':'North Ave',
  'North Ave &amp; Charles St':'North Ave',
  'North Ave Market':'North Avenue Market',
  'North Ave. Market':'North Avenue Market',
  'North Avenue Market':'North Avenue Market',
  'North Charles and 33rd St':'North Charles and 33rd St',
  'Of Love And Regret':'Of Love And Regret',
  'Old Line Spirits':'Old Line Spirits',
  'Old Major':'Old Major',
  'Old Major (900 S. Carey St.)':'Old Major',
  'Old York Lot':'Old York Lot',
  'Old York Lot (outdoors - message bands for address)':'Old York Lot',
  'Oliver Brewing Company':'Oliver Brewing Company',
  'Oliver Brewing Company (Outside)':'Oliver Brewing Company',
  'Onle Vibez':'Onle Vibez',
  'Onle Vibez (3241 Belar Rd)':'Onle Vibez',
  'Online on Twitch':'No address listed',
  'Orion Studios':'Orion Studios',
  'OttobaR':'Ottobar',
  'Ottobar':'Ottobar',
  'Ottobar Patio':'Ottobar',
  'Ottobar Upstairs':'Ottobar',
  'Ottobar Upstairs<br>Metroschock. 9PM, $10 @ Metro Gallery':'Ottobar',
  'Ottobar&nbsp;':'Ottobar',
  'OttobarCell, Myopic, Skaldr, Egalabalus. @ Sidebar':'Ottobar',
  'Outside (DM bands for address)':'No address listed, DM for address',
  'P.A.L.M.':'P.A.L.M.',
  'P.A.L.M. (25 E Cross St)':'P.A.L.M.',
  'P.A.L.M. (25 E. Cross St)':'P.A.L.M.',
  'PP Palace':'PP Palace',
  'PP Palace (DM bands for address)':'PP Palace',
  'Palm (25 E. Cross St.)':'P.A.L.M.',
  'Pariah Brewing':'Pariah Brewing',
  'Pariah Brewing Company':'Pariah Brewing',
  'Parkway Theatre':'Parkway Theatre',
  'Parkway Theatre + MICA':'Parkway Theatre',
  'Parris Underground':'Parris Underground',
  'Parris Underground (497 Ritchie Highway Suite C)':'Parris Underground',
  'Patapsco Valley Park (Hollofield 301)':'Patapsco Valley Park (Hollofield 301)',
  'Patriot Plaza':'Patriot Plaza',
  'Patteron Park Pagoda':'Patterson Park',
  'Patterson Park':'Patterson Park',
  'Patterson Park (2800 Eastern &amp; Linwood Aves)':'Patterson Park',
  'Patterson Park (northwest corner)':'Patterson Park',
  'Patterson Park Observatory':'Patterson Park',
  'Patterson Park Pagoda':'Patterson Park',
  'Patterson Park Pagoda Observatory':'Patterson Park',
  'Patterson Park Pulaski Monument':'Patterson Park',
  'Peabody Brewing':'Peabody Heights Brewery',
  'Peabody Height Brewery':'Peabody Heights Brewery',
  'Peabody Heights':'Peabody Heights Brewery',
  'Peabody Heights Brewery':'Peabody Heights Brewery',
  'Peabody Heights Brewery</strike>':'Peabody Heights Brewery',
  'Peabody Heights Brewing':'Peabody Heights Brewery',
  'Peabody Maestro’s Cafe':'Peabody Maestro’s Cafe',
  'Pearlstone Park':'Pearlstone Park',
  'Penn &amp; Baker St.':'Penn and Baker St',
  'Penn and Baker St':'Penn and Baker St',
  'Phlote':'Phlote',
  'Phlote (300 W Pratt St 3rd floor)':'Phlote',
  'Phlote (300 W Pratt St)':'Phlote',
  'Phoenix Art Yard (1320 Bayard St)':'Phoenix Art Yard (1320 Bayard St)',
  'Phoenix Cultural':'Phoenix Cultural',
  'Pier Six':'Pier Six',
  'Pier Six Pavilion':'Pier Six',
  'Pigtango Bakery &amp; Cafe':'Pitango Bakery &amp; Cafe',
  'Pink Lounge':'Pink Lounge',
  'Pique Collective':'Pique Collective',
  'Pitango Bakery &amp; Cafe':'Pitango Bakery &amp; Cafe',
  'Polish Home Club':'Polish Home Club',
  'Port Covington':'Port Covington',
  'Power Plant':'Mosaic',
  'Power Plant Live':'Mosaic',
  'Powerplant':'Mosaic',
  'Powerplant Live':'Mosaic',
  'Pratt St &amp; Ellwood Ave':'Pratt St and Ellwood Ave',
  'Pratt St and Ellwood Ave':'Pratt St and Ellwood Ave',
  'Purchase tickets for address':'No address listed',
  'Purr Palace':'Purr Palace',
  'Purr Palace (DM bands for address)':'Purr Palace',
  'Pussy Palace':'Pussy Palace',
  'Pussy Palace (DM bands for address)':'Pussy Palace',
  'R House':'R House',
  'R House Garage &amp; Patio':'R House',
  'R. House Garage':'R House',
  'RItuals':'Rituals',
  'Racers Cafe (7732 Harford Rd - outside)':'Racers Cafe (7732 Harford Rd - outside)',
  'Rams Head':'Rams Head',
  'Rams Head Live':'Rams Head',
  'Rams Head<br>Usher. 8PM, $260 @ CFG Arena':'Rams Head',
  'Raw &amp; Refined':'Raw and Refined',
  'Raw &amp; Refined (2723 Lighthouse Point)':'Raw and Refined',
  'Raw and Refined':'Raw and Refined',
  'Recher':'Recher',
  'Red Emma&rsquo;s':'Red Emma’s',
  'Red Emma’s':'Red Emma’s',
  'Red Room':'Normal’s Books',
  'Remington Ave':'Remington Ave',
  'Remington Ave &amp; 28th St':'Remington Ave and 28th St',
  'Remington Ave (Remington Ave &amp; 28th St)':'Remington Ave',
  'Remington Ave and 28th St':'Remington Ave and 28th St',
  'Renaissance Harborplace Hotel':'Renaissance Harborplace Hotel',
  'Reverb':'Reverb',
  'Rituals':'Rituals',
  'Robert &amp; Bolton St':'Robert and Bolton St',
  'Robert C. Marshall Park':'Robert C. Marshall Park',
  'Robert and Bolton St':'Robert and Bolton St',
  'Rocket To Venus':'Rocket to Venus',
  'Rocket To Venus  <br />':'Rocket to Venus',
  'Rocket to Venus':'Rocket to Venus',
  'Roland Park Community Center':'Roland Park Community Center',
  'Roland Water Tower':'Roland Water Tower',
  'Roland Water Tower':'Roland Water Tower',
  'Roland Water Tower (4210 Roland Ave)':'Roland Water Tower',
  'Roosevelt Park (36th St &amp; Falls Rd)':'Hampden Park',
  'Route begins at North Charles and 33rd St.':'North Charles and 33rd St',
  'Royal Blue':'Royal Blue',
  'Royal Blue  <br />':'Royal Blue',
  'Royal Rumble':'Royal Rumble',
  'Rumble Room':'Rumble Room',
  'Rumble Room (DM artists for address)':'Rumble Room',
  'SIsson St Community Park':'Sisson Street Community Park',
  'Salt Pepper Ketchup (1118 Hollins St)':'1118 Hollins St',
  'Sandy Hill Skatepark':'Lansdowne Skatepark',
  'Saunter Corner Bar':'1801 Bar',
  'Secret Beach':'Secret Beach',
  'Secret Beach (DM bands for address)':'Secret Beach',
  'Secret Location Downtown Baltimore (DM On Point Events for info)':'No address listed, DM for address',
  'Shake &amp; Bake':'Shake and Bake',
  'Shake &amp; Bake Family Fun Center':'Shake and Bake',
  'Shake and Bake':'Shake and Bake',
  'Shake n’ Bake':'Shake and Bake',
  'Shake'n'Bake Family Fun Center':'Shake and Bake',
  'Shamrock Inn':'Shamrock Inn',
  'Sicilys':'Sicilys',
  'Side Door (DM bands for address)':'Sidedoor',
  'Sidebar':'Sidebar',
  'Sidebar</a>':'Sidebar',
  'Sidedoor':'Sidedoor',
  'Sidedoor   (DM SidedoorsBaltimore for addy)':'Sidedoor',
  'Sidedoor (DM SidedoorsBaltimore for addy)':'Sidedoor',
  'Sidedoor (DM bands for address)':'Sidedoor',
  'Sisson Street Community Park':'Sisson Street Community Park',
  'Skate Park of Baltimore':'Hampden Skate Park',
  'Skatepark of Baltimore':'Hampden Skate Park',
  'Skatepark of Bmore':'Hampden Skate Park',
  'Sky Tower':'Sky Tower',
  'Sky Tower (DM bands for address)':'Sky Tower',
  'Snack Castle Castle':'Snack Castle Castle',
  'Snack Castle Castle (DM bands for address)':'Snack Castle Castle',
  'Sound Garden':'Sound Garden',
  'Sound Garden':'Sound Garden',
  'Soundgarden Records':'Sound Garden',
  'Southpaw':'Southpaw',
  'Southpaw (529 S Bond St)':'Southpaw',
  'Southwest Corner of Patterson Park':'Southwest Corner of Patterson Park',
  'Space 2640':'2640 Space',
  'Space 4321':'Space 4321',
  'Space 4321 (4321 Harford Rd)':'Space 4321',
  'Spirits of Mt Vernon':'Spirits of Mt Vernon',
  'Squeak':'Squeak',
  'Squeak (call 877-577-BOOM for address)':'Squeak',
  'St David’s Episcopal Church':'St David’s Episcopal Church',
  'St Luke’s Church':'St Luke’s Church',
  'St Mary’s Park':'St Mary’s Park',
  'St Mary’s Restaurant':'St Mary’s Restaurant',
  'St Mary’s Restaurant (120 W 25th St)':'St Mary’s Restaurant',
  'St Nicholas Church':'St Nicholas Church',
  'St. David’s Episcopal Church (4700 Roland Ave)':'St David’s Episcopal Church',
  'St. David’s Episcopal Church of Roland Park':'St David’s Episcopal Church',
  'St. Luke’s Church':'St Luke’s Church',
  'St. Luke’s Church (800 W 36th St)':'St Luke’s Church',
  'St. Mary’s Park':'St Mary’s Park',
  'St. Mary’s Upstairs (120 W. 25th St)':'St Mary’s Restaurant',
  'Starts at YNOT Lot':'YNOT Lot',
  'Station North':'North Ave',
  'Station North (DM bands for address)':'No address listed, DM for address',
  'Stem &amp; Vine':'Stem and Vine',
  'Stem and Vine':'Stem and Vine',
  'Stevenson Ranch':'Stevenson Ranch',
  'Stoneleigh Lanes':'Stoneleigh Lanes',
  'Studio 10':'Studio 10',
  'Studio Ten 10':'Studio 10',
  'Submersive HQ':'Submersive HQ',
  'Submersive HQ (3523 Buena Vista Ave)':'Submersive HQ',
  'Sweet 27':'Sweet 27',
  'Tacos Tijuana':'Tacos Tijuana',
  'Tacos Tijuana (1709 Edgewood Rd)':'Tacos Tijuana',
  'Tarantula Hill':'Tarantula Hill',
  'Terra Cafe':'Terra Cafe',
  'Terra Cafe (outdoors)':'Terra Cafe',
  'The Ave in Hampden':'Hampden',
  'The Bank (1901 N Charles)':'1901 N Charles St',
  'The Biddle':'The Biddle',
  'The Biddle (1 W Biddle St)':'The Biddle',
  'The Bluebird':'De Kleine Duivel',
  'The Bun Shop':'The Bun Shop',
  'The Calbox':'The Calbox',
  'The Calbox (DM bands for address)':'The Calbox',
  'The Can Company':'The Can Company',
  'The Carroll Mansion':'The Carroll Mansion',
  'The Castle':'The Castle',
  'The Castle (DM bands for address)':'The Castle',
  'The Cat’s House':'The Cat’s House',
  'The Cat’s House (DM bands for address)':'The Cat’s House',
  'The Cave':'The Cave',
  'The Cave (DM bands for address)':'The Cave',
  'The Cigarette Jar':'The Cigarette Jar',
  'The Cigarette Jar (DM bands for address)':'The Cigarette Jar',
  'The Compound':'The Compound',
  'The Compound (2239 Kirk Ave)':'The Compound',
  'The Compound (DM bands for address)':'The Compound',
  'The Compound&nbsp;  (2239 Kirk Ave)':'The Compound',
  'The Copycat':'The Copycat',
  'The Copycat (6th floor)':'The Copycat',
  'The Deport':'The Deport',
  'The Depot':'The Deport',
  'The Empanada Lady':'The Empanada Lady',
  'The Eubie (847 N. Howard)':'Eubie Blake Cultural Center',
  'The Forest':'The Forest',
  'The Forest (DM ___by_my_reanimated_corpse for address)':'The Forest',
  'The Forest (DM bands for address)':'The Forest',
  'The Forest (DM bmorezinefest for address)':'The Forest',
  'The Fort':'The Fort',
  'The Fort (DM bands for address)':'The Fort',
  'The Green Room':'De Kleine Duivel',
  'The Green Room (3602 Hickory Ave.)':'De Kleine Duivel',
  'The H.O.L.E. (DM bmorezinefest for address)':'The Hole',
  'The Hargrove':'The Hargrove',
  'The Hargrove':'The Hargrove',
  'The Hargrove (2223 Hargrove St)':'The Hargrove',
  'The Hargrove (2225 Hargrove Aly)':'The Hargrove',
  'The Hargrove (DM artists for address)':'The Hargrove',
  'The Hippodrome':'Hippodrome',
  'The Hole':'The Hole',
  'The Hole (DM bands below for address)':'The Hole',
  'The Hole (DM bands for address)':'The Hole',
  'The Hole (DM bmorezinefest for address)':'The Hole',
  'The Hole Severna Park (DM bands for address)':'The Hole',
  'The Jaded Lounge':'The Jaded Lounge',
  'The Lou Costello Room Comedy Club':'Zissimos',
  'The Lyric':'The Lyric',
  'The Lyric</strike>':'The Lyric',
  'The Lyric<br>“Wrong Way” w/ MR Sauter &amp; Joanne McNeil. 7PM, $FREE @ Red Emma’s':'The Lyric',
  'The Manor':'The Manor',
  'The Modell Lyric':'The Lyric',
  'The Office (300 W. Pratt St)':'Phlote',
  'The Ottobar':'Ottobar',
  'The Parlor (108 W. North Ave.)':'The Parlor (108 W. North Ave.)',
  'The Parlor (803 St. Paul)':'The Parlor (803 St. Paul)',
  'The Peale':'The Peale',
  'The Pearl Gallery':'The Pearl Gallery',
  'The Point':'The Point',
  'The Recher':'Recher',
  'The Reservoir':'The Reservoir',
  'The Rockwell':'The Rockwell',
  'The Royal Blue':'Royal Blue',
  'The Ruins':'The Ruins',
  'The Ruins (DM bands for address)':'The Ruins',
  'The Ruins (DM nfc.underground for address)':'The Ruins',
  'The Shamrock Inn':'Shamrock Inn',
  'The Skatepark':'The Skatepark',
  'The Skatepark (DM bands for address)':'The Skatepark',
  'The Sound Garden':'Sound Garden',
  'The Undercroft':'The Undercroft',
  'The Vortex':'The Vortex',
  'The Vortex (CAA Park)':'The Vortex',
  'The Vortex CAA Park':'The Vortex',
  'The Vortex at CAA Park':'The Vortex',
  'The Voxel':'The Voxel',
  'The Voxel (9 W 25th St) [FREE stream: <a href="http://twitch.tv/mofbaltimore">twitch.tv/mofbaltimore</a>]':'The Voxel',
  'The Voxel (9 W 25th St) [FREE stream:&nbsp;<a href="http://twitch.tv/mofbaltimore">twitch.tv/mofbaltimore</a>]':'The Voxel',
  'The Watermelon Room (DM bands for address)':'Watermelon Room',
  'The Waverly Commons':'Waverly Commons',
  'The Wiggle Room':'The Wiggle Room',
  'The Wiggle Room (3000 Falls Rd)':'The Wiggle Room',
  'The Wine Collective':'The Wine Collective',
  'The Wren':'The Wren',
  'Thee Portal':'Thee Portal',
  'Thee Portal (DM artists for address)':'Thee Portal',
  'Thee Portal (DM bands for address)':'Thee Portal',
  'Thee Portal (DM for address)':'Thee Portal',
  'Topside':'Topside',
  'Towson Planetarium':'Towson Planetarium',
  'Trophy House':'Trophy House',
  'Trophy House/4 q u a r i u m (email suzannedoogan at gmail dot com for address)':'Trophy House',
  'True Vine':'True Vine',
  'True Vine Record Shop':'True Vine',
  'True Vine Records':'True Vine',
  'UC Ballroom':'UC Ballroom',
  'Undercroft':'The Undercroft',
  'Undercroft (outdoors)':'The Undercroft',
  'Union Square Park':'Union Square Park',
  'Union Square Park (31 S. Gilmor St)':'Union Square Park',
  'University of Baltimore (Wright Theater)':'University of Baltimore Student Center Auditorium',
  'University of Baltimore Student Center Auditorium':'University of Baltimore Student Center Auditorium',
  'University of Baltimore Student Center Auditorium 5th floor (SE Corner Mt Royal &amp; Maryland)':'University of Baltimore Student Center Auditorium',
  'Uranus':'Uranus',
  'Uranus (DM bands for address)':'Uranus',
  'Village Learning Place':'Village Learning Place',
  'Village Learning Place (2521 St. Paul St)':'Village Learning Place',
  'WAX ATLAS (22 W 25th St.)':'Wax Atlas',
  'War Memorial Plaza':'War Memorial Plaza',
  'War Memorial Plaza (101 N. Gay St)':'War Memorial Plaza',
  'Warehouse':'Warehouse',
  'Warehouse (DM @theeronwesley for address)':'Warehouse',
  'Warehouse (DM for address)':'Warehouse',
  'Warehouse (tix on Resident Advisor)':'Warehouse',
  'Warehouse Cinema':'Warehouse Cinema',
  'Warehouse Cinema Rotunda':'Warehouse Cinema',
  'Warehouse Cinemas':'Warehouse Cinema',
  'Watermelon Room':'Watermelon Room',
  'Watermelon Room (DM bands for address)':'Watermelon Room',
  'Watermelon Room (DM bands for tix+address)':'Watermelon Room',
  'Waverly Brewery Company':'Waverly Brewery Company',
  'Waverly Brewing':'Waverly Brewery Company',
  'Waverly Brewing Co.':'Waverly Brewery Company',
  'Waverly Brewing Company':'Waverly Brewery Company',
  'Waverly Commons':'Waverly Commons',
  'Waverly Commons (32nd St &amp; Brentwood Ave)':'Waverly Commons',
  'Waverly Commons (418 E 32nd St)':'Waverly Commons',
  'Waverly Craft Brewing':'Waverly Brewery Company',
  'Waverly Main St':'Waverly Main St',
  'Waverly United Methodist':'Waverly United Methodist',
  'Wax Atlas':'Wax Atlas',
  'Wax Atlas':'Wax Atlas',
  'Wax Atlas Records':'Wax Atlas',
  'Weiss Imports &amp; Domestics (1160 Homestead St)':'Weiss Imports and Domestics',
  'Weiss Import and Domestics':'Weiss Imports and Domestics',
  'Weiss Import &amp; Domestic':'Weiss Imports and Domestics',
  'Weiss Imports and Domestics':'Weiss Imports and Domestics',
  'Whitelock Community Farm':'Whitelock Community Farm',
  'Whitelock Community Farm (930 Whitelock St. 21217)':'Whitelock Community Farm',
  'Wico St. Beer Company':'Grass Bmore',
  'Wico Street Beer Co.':'Grass Bmore',
  'Wiggle Room (3000 Falls Rd)':'The Wiggle Room',
  'Wiggle Room (DM bands for address)':'The Wiggle Room',
  'Wine Collective':'The Wine Collective',
  'Wright Theater (University of Baltimore)':'University of Baltimore Student Center Auditorium',
  'Wxterhouse Studio':'Wxterhouse Studio',
  'Wxterhouse Studio (2202 Boston St)':'Wxterhouse Studio',
  'Wyman Park':'Wyman Park Dell',
  'Wyman Park Baseball Diamond':'Wyman Park Baseball Diamond',
  'Wyman Park Baseball Diamond (West 37th &amp; Beech Ave)':'Wyman Park Baseball Diamond',
  'Wyman Park Dell':'Wyman Park Dell',
  'YNOT LOT':'YNOT Lot',
  'YNOT Lot':'YNOT Lot',
  'Ye Olde Emerald Tavern':'Ye Olde Emerald Tavern',
  'Ynot Lot':'YNOT Lot',
  'Ynot Lot (4PM)/True Vine (3PM)':'YNOT Lot',
  'York Rd &amp; Woodbourne Ave':'York Rd and Woodbourne Ave',
  'York Rd and Woodbourne Ave':'York Rd and Woodbourne Ave',
  'Zen West':'Zen West',
  'Zen West<br>Sierra Hull. 7PM, $38.80-$59 @ The Recher':'Zen West',
  'Zika Farm':'Zika Farm',
  'Zika Farm (Address shown w/ ticket purchase)':'Zika Farm',
  'Zika Farm (DM artists for address)':'Zika Farm',
  'Zika Farm (DM bands for address)':'Zika Farm',
  'Zika Farm (DM data_mine for address)':'Zika Farm',
  'Zika Farm (use QR code on flyer for location)':'Zika Farm',
  'Zion Lutheran Church':'Zion Lutheran Church',
  'Zion Lutheran Church (400 E Lexington St)':'Zion Lutheran Church',
  'Zissimos':'Zissimos',
  'Zissimos Bar':'Zissimos',
  'Zissimos</strike>':'Zissimos',
  'Zissimo’s':'Zissimos',
  'Zo Gallery (3510 Ash St)':'3510 Ash St',
  'Zoo Pavillion':'Zoo Pavillion',
  'Zoo Pavillion (1 Safari Place)':'Zoo Pavillion',
  'aquarium':'4 q u a r i u m',
  'jackson_s_house (806 Berry St)':'Jacksons House',
}
