list_of_venues = [
['1 E Baltimore St', ['1 E Baltimore St','1 E. Baltimore St']],
['101 E Pratt St', ['101 E Pratt St']],
['1100 Hollins St', ['1100 Hollins St', '1100 Hollins St.']],
['1117 E 36th St', ['1117 E 36th St']],
['1118 Hollins St', ['1118 Hollins St', 'City of Gods', 'Salt Pepper Ketchup (1118 Hollins St)']],
['1128 Hollins St.', ['1128 Hollins St.']],
['1217 E Preston St', ['1217 E Preston St','1217 E. Preston St']],
['13.5 Wine Bar', ['13.5 Wine Bar']],
['1300 Bayard St', ['1300 Bayard St']],
['1420 Eutaw St', ['1420 Eutaw St']],
['1423 John St', ['1423 John St']],
['1443 Riverside Ave', ['1443 Riverside Ave']],
['1500 McCulloh St', ['1500 McCulloh St','1500 Mcculloh St']],
['1505 Eutaw Pl', ['1505 Eutaw Pl','1505 Eutaw PL']],
['1627 E Fort Ave', ['1627 E Fort Ave']],
['1701 N Charles St', ['1701 N Charles St','1701 N Charles St./Crown/Rituals/Annex Lounge','1701 N. Charles St./Crown/Rituals/Annex Lounge']],
['1709 N Charles St', ['1709 N Charles St']],
['1750 Union Ave', ['1750 Union Ave']],
['1801 Bar', ['1801 Bar', 'Bar 1801', 'Saunter Corner Bar']],
['1801 St Paul St', ['1801 St Paul St']],
['1810 Webster St', ['1810 Webster St']],
['1828 Webster St', ['1828 Webster St']],
['1901 N Charles St', ['1901 N Charles St', 'Charles St. between North Ave. and 23rd St.', 'The Bank (1901 N Charles)']],
['1915 Maryland Ave', ['1915 Maryland Ave','1915 Maryland Avenue']],
['1919', ['1919', '1919 Fleet St']],
['200 Read St', ['200 Read St','200 Block of Read St','200 Block of Read St.']],
['200 St Paul Pl', ['200 St Paul Pl','200 St Paul Place','200 St. Paul Place']],
['2010 Clipper Park Rd Suite 105', ['2010 Clipper Park Rd Suite 105']],
['2100 Liberty Heights', ['2100 Liberty Heights']],
['218 W Saratoga St', ['218 W Saratoga St', '218 West Saratoga St']],
['2200 Eutaw St', ['2200 Eutaw St','2200 Eutaw St.']],
['2401 N Rose St', ['2401 N Rose St','2401 N. Rose St','2401 N. Rose St.']],
['2407 Ken Oak Road', ['2407 Ken Oak Road']],
['2410 Erdman Ave', ['2410 Erdman Ave']],
['2412 College Ave', ['2412 College Ave']],
['2610 St Paul St', ['2610 St Paul St']],
['2613 Talbot Rd', ['2613 Talbot Rd']],
['2640 Space', ['2640 Space', 'Space 2640']],
['26th and Guilford', ['26th and Guilford']],
['27 S Patterson Park', ['27 S Patterson Park']],
['2703 Halcyon Ave', ['2703 Halcyon Ave']],
['2741 Guilford Ave', ['2741 Guilford Ave', '2741 Guilford Ave.']],
['2801 N Calvert St', ['2801 N Calvert St']],
['2925 Heswick Rd', ['2925 Heswick Rd']],
['2999 Boston St', ['2999 Boston St']],
['29th St and Charles St', ['29th St and Charles St','29th St &amp; Charles St', 'N. Charles St &amp; 29th St']],
['30 W North Ave', ['30 W North Ave','30 West North Ave','30 West North Ave.']],
['Mobtown Ballroom', ['Mobtown Ballroom', 'Mobtown Ballroom &amp; Club Car &amp; Royal Blue &amp; Night Owl']],
['North Avenue Market', ['North Avenue Market','North Ave Market', 'North Ave. Market']],
['3000 Abell Ave', ['3000 Abell Ave','3000 Block of Abell Ave.']],
['3001 East Dr', ['3001 East Dr','3001 East Dr.']],
['301 McMechen St', ['301 McMechen St']],
['307 Northway', ['307 Northway']],
['3126 Weaver Ave', ['3126 Weaver Ave']],
['3137 Eastern Ave. Baltimore', ['3137 Eastern Ave. Baltimore']],
['3209 Rosalie Ave', ['3209 Rosalie Ave']],
['321 E. 28th St', ['321 E. 28th St']],
['32nd St and Brentwood', ['32nd St and Brentwood','32nd St &amp; Brentwood', '32nd St &amp; Brentwood Ave', '32nd St &amp; Brentwood Ave.', '32nd St. &amp; Brentwood Ave']],
['3300 Clipper Mill Rd', ['3300 Clipper Mill Rd']],
['3308 Glenmore Ave', ['3308 Glenmore Ave']],
['3311 Ailsa Ave', ['3311 Ailsa Ave']],
['3355 Keswick Rd', ['3355 Keswick Rd','3355 Keswick']],
['3510 Ash St', ['3510 Ash St', 'Zo Gallery (3510 Ash St)']],
['3531 Chestnut Ave', ['3531 Chestnut Ave','3531 Chestnut Ave. (outdoors)']],
['3539 Clipper Mill Rd', ['3539 Clipper Mill Rd', '3539 Clipper Mills Rd']],
['4000 Buena Vista Ave', ['4000 Buena Vista Ave']],
['4001 Harford Rd', ['4001 Harford Rd']],
['406 N. Howard St', ['406 N. Howard St']],
['4127 Westview Rd', ['4127 Westview Rd']],
['4303 Maine Ave', ['4303 Maine Ave']],
['431 Notre Dome Lane', ['431 Notre Dome Lane']],
['4500 Harford Rd', ['4500 Harford Rd','4500 Harford Rd (outdoors)', '4500 Harford Road', 'Montebello Terrace (4500 Harford Road)']],
['4518 Raspe Ave', ['4518 Raspe Ave', 'Lwn Sphere (4518 Raspe Ave)', 'Lwnsphere (4518 Raspe Ave)']],
['4 q u a r i u m', ['4 q u a r i u m', '4QUARIAM', '4quarium', '4quarium (DM bands for address)','Aquarium','aquarium']],
['5003 Grindon Ave', ['5003 Grindon Ave']],
['507 N Carrollton Ave', ['507 N Carrollton Ave']],
['5401 Elsrode Ave', ['5401 Elsrode Ave', '5401 Elsrode Ave.']],
['5605 Tramore Rd', ['5605 Tramore Rd']],
['5701 Smith Ave', ['5701 Smith Ave']],
['5816 Catalpha Rd', ['5816 Catalpha Rd']],
['5D (ask the SHRYMPS for address)',['5D (ask the SHRYMPS for address)']],
['6 E. Franklin St', ['6 E. Franklin St']],
['6007 Pinehurst Rd', ['6007 Pinehurst Rd']],
['604 Hollen Road', ['604 Hollen Road']],
['604 Roundview Road', ['604 Roundview Road']],
['6207 Blackburn LN', ['6207 Blackburn LN', '6207 Blackburn Lane', '6207 Blackburn Ln']],
['636 Deepdene Rd', ['636 Deepdene Rd']],
['701 Ponca St', ['701 Ponca St']],
['720 E 30th St', ['720 E 30th St','720 E. 30th St.']],
['810 W. 36th St', ['810 W. 36th St']],
['817 N Howard St', ['817 N Howard St','817 N. Howard St','817 N. Howard St.']],
['825 Montpelier St', ['825 Montpelier St','825 Montpelier St.']],
['8x10', ['8X10', '8x10']],
['Abbey Burger Bistro', ['Abbey Burger Bistro']],
['Abell Ave', ['Abell Ave', 'Abell St.']],
['Alchemy of Art', ['Alchemy of Art','Alchemy of Art (1637 Eastern Ave)']],
['Aliceanna Social Club', ['Aliceanna Social Club', 'Aliceanna Social Club (1603 Aliceanna St)']],
['American Legion Post 38', ['American Legion Post 38','American Legion Post 38 (3300 Dundalk Ave)']],
['American Visionary Arts Museum', ['American Visionary Arts Museum']],
['An die Musik', ['An Die Musik', 'An Die Musik Live', 'An Die Musk', 'An die Musik']],
['Angels Rock Bar', ['Angels Rock Bar', 'Angel’s Rock Bar']],
['Annex Lounge', ['Annex Lounge']],
['Area 405', ['405 E Oliver St', 'Area 405']],
['Arnolds', ['Arnolds','Arnolds (118 W Mulberry St)', 'Grn Drgn Cafe (118 West Mulberry St)']],
['Asian Taste', ['Asian Taste']],
['Atomic Books', ['Atomic Books']],
['B&O Railroad Museum', ['B&O Railroad Museum','B&amp;O Railroad Museum']],
['Baltimore Spirits Company', ['BSC Cocktail Gallery', 'BSC’s Cocktail Gallery', 'Baltimore Spirits Company', 'Cocktail Gallery']],
['Barclay House',['Barclay House (DM Bands for address)', 'Barclay House (DM bands for address)']],
['BSC Cocktail Gallery', ['BSC Cocktail Gallery', 'BSC’s Cocktail Gallery', 'Baltimore Spirits Company', 'Cocktail Gallery', 'The Wine Collective', 'Union Craft', 'Union Craft Brewery', 'Union Craft Brewing', 'Union Craft Brewing&nbsp;', 'Wine Collective', 'Wonderground Park']],
['Union Craft Brewing', ['Union Craft', 'Union Craft Brewery', 'Union Craft Brewing', 'Union Craft Brewing&nbsp;']],
['Wonderground Park', ['Wonderground Park']],
['The Meyerhoff', ['BSO', 'The Meyerhoff']],
['Baby’s on Fire', ['Baby’s on Fire']],
['Baltimore City Hall', ['Baltimore City Hall', 'City Hall']],
['Baltimore Clayworks', ['Baltimore Clayworks']],
['Baltimore Museum of Industry', ['Baltimore Museum of Industry', 'Museum of Industry', 'Museum of Industry Pavilion']],
['Baltimore Safe Haven', ['Baltimore Safe Haven', 'Maryland Safe Haven']],
['Baltimore Science Fiction Society', ['Baltimore Science Fiction Society']],
['Baltimore Soundstage', ['Baltimore Soundstage', 'Soundstage', 'Soundstage<br>Karaoke. 8PM, $FREE @ Old Major']],
['Baltimore Theater Project', ['Baltimore Theater Project', 'Baltimore Theatre Project', 'Theatre Project']],
['Barcocina', ['Barcocina']],
['Bazaar', ['Bazaar','Bazaar (3534 Chestnut Ave)']],
['Beyond Video', ['Beyond Video']],
['BF House',['BF House']],
['Big Blue House',['Big Blue House (DM bands for address)']],
['Bird In Hand', ['Bird In Hand']],
['Black Acres Coffee', ['Black Acres Coffee', 'Open Works', 'Openworks (1400 Greenmount Ave)']],
['Black Cherry Puppet Theater', ['Black Cherry Pupper Theater', 'Black Cherry Puppet Theater', 'Black Puppet Cherry Theater']],
['Black Collar', ['Black Collar']],
['Bliss Meadows', ['Bliss Meadows','Bliss Meadows (5105 Plainfield Ave)', 'Bliss Meadows (5105 Plainfield Avenue)']],
['Bloom’s', ['Bloom’s']],
['Bogus Gallery', ['Bogus Gallery','Bogus Gallery (1511 Guilford Ave)']],
['Bone Haus',['Bone Haus']],
['Bone Orchard',['Bone Orchard (DM bands for address)','The Bone Orchard (DM bands for address)']],
['Book Thing', ['Book Thing', 'The Book Thing']],
['Bramble Bakery', ['Bramble Bakery','Bramble Bakery (5414 Harford Rd)', 'Bramble Bakery Co.', 'Bramble Baking Co.', 'Bramble Baking Co. (5414 Harford Rd)']],
['Bromo Arts District', ['Bromo Arts District']],
['Burns Manor',['Burns Manor']],
['CFG Arena', ['CFG Arena', 'CFG Bank Arena']],
['Camden Yards', ['Camden Yards']],
['Canton Waterfront Park', ['Canton Waterfron Park', 'Canton Waterfront Park', 'Canton Waterfront Park,']],
['Capital Lounge', ['1531 Pennsylvania Ave','1531 Pennsylvania Ave.', 'Capital Lounge']],
['Carroll Skatepark', ['Carroll Skatepark','Caroll Skatepark']],
['Catbody',['Catbody (message bands for address)']],
['Cat City', ['Cat City','Cat City (2741 Guilford Ave)', 'Cat House (2741 Guilford Ave)', 'Cat House (DM artists for address)', 'Cat House (DM bands for address)']],
['Center Plaza', ['Center Plaza','Center Plaza (110 W. Fayette St)']],
['Center Stage', ['Center Stage']],
['Ceremony Coffee Harbor East', ['Ceremony Coffee Harbor East', 'Ceremony Coffee Harbor Point']],
['Chap',['Chap (DM bands for address)']],
['Chapel of Church of the Redeemer', ['Chapel of Church of the Redeemer']],
['Chapterhouse Tattoo', ['Chapterhouse Tattoo']],
['Charles St', ['Charles St', 'Downtown']],
['Charles Theatre', ['Charles Theater', 'Charles Theatre']],
['Charm City Books', ['Charm City Books']],
['Charm City Meadworks', ['Charm City Meadworks', 'Charm City Meadworks (outdoors)']],
['Charm City Skatepark', ['Charm City Skatepark', 'Charmcity Skatepark']],
['Checkerspot Brewing', ['Checkerspot Brewing', 'Checkspot Brewing']],
['Chilton St and Hillen Road', ['Chilton St and Hillen Road','Chilton St &amp; Hillen Road']],
['Chimney Swallow',['Chimney Swallow (DM bands for address)']],
['Church on the Square', ['1025 S Potomac St', 'Church on the Square', 'Music on the Square']],
['City Beach',['City Beach', 'City Beach Live']],
['Clifton Park Bandshell', ['Clifton Bandshell', 'Clifton Park Bandshell']],
['Clifton Park', ['Clifton Park']],
['Clifton Pleasure Club', ['Clifton Pleasure Club']],
['Clovr Collective', ['Clovr Collective', 'Clovr Collective (2010 Clipper Park Road)', 'Clovr Collective (DM bands for address)']],
['Club 1722', ['1722 N Charles St', 'Club 1722 (1722 N Charles St)']],
['Club 603',['Club 603', 'Club 603 (outside)']],
['Club Car', ['12 to 30 West North Ave', 'Club Car', 'Club Car (12 W. North Ave)', 'Club Car.', 'Club Carr']],
['Comptoir Du Vin', ['Comptoir Du Vin', 'Comptoir du Vin', 'Le Comptoir Du Vin', 'Le Comptoir du Vin']],
['Cotyledon Arts', ['Cotyledon Arts','Cotyledon Arts (422 Mulberry W St)']],
['Creative Alliance', ['Creative Alliance', 'Creative Alliance &nbsp;', 'Creative Alliance&nbsp;', 'Creative Alliance.']],
['Crown', ['Crown', 'Crown Back Back', 'Crown Back Bar', 'Crown Pink Room', 'Crown Pink Room + Back Bar', 'Crown&nbsp;', 'Crown/Y Not Lot', 'The Crown', 'The Crown (both floors)', 'The Crown.']],
['Cult Classic Brewing', ['Cult Classic Brewing']],
['Current Space', ['421 N Howard St', 'Current Space', 'Current Space  <br />']],
['Cylburn Arboretum', ['Cylburn Arboretum']],
['Dangerously Delicious', ['Dangerously Delicious','Dangerously Delicious (810 36th St)', 'Dangerously Delicious Hampden (810 W. 36th St)', 'Dangerously Delicious Pies']],
['Dark Room (DM bands for address)', ['DarkRoom', 'DarkRoom (DM DarkRoom for address)', 'DarkRoom (DM bands for address)', 'DarkRoom (DM bands for address)<br>Beaucoup De Chapeaux. 5PM-8PM @ Union Craft Brewing', 'DarkRoom (DM for address)', 'DarkRoom (email deepsidebaltimore@gmail.com for info)', 'DarkRoom (email deepsidebaltimore@gmail.com for location)', 'DarkRoom (email deepsidebaltimore@gmail.com)', 'Darkroom', 'Darkroom (DM bands for address)']],
['De Kleine Duivel', ['De Kleine Duivel', 'The Bluebird', 'The Green Room', 'The Green Room (3602 Hickory Ave.)']],
['Dear Globe Coffeebar', ['Dear Globe Coffeebar']],
['Design Distillery', ['Design Distillery','Design Distillery (1414 Key Hwy)', 'Design Distillery (21414 Key Hwy)']],
['Dick’s Halfway Inn', ['Dick’s Halfway Inn']],
['Digital Xscape',['Digital Xscape','Digital Xscape (DM digitalxscape for address)', 'Digital Xscape (DM for Address)']],
['Disconsin',['Disconsin', 'Disconsin (DM bands for address)', 'Disconsin (message artists for address)', 'Disconsin (message bands for address)']],
['Dog House Mansion', ['Dog House Mansion','Dog House Mansion (5607 Roland Ave)']],
['Don’t Know Tavern', ['Don’t Know Tavern']],
['Douglas Memorial Church', ['Douglas Memorial Church', 'Douglas Memorial Community Church']],
['Dream Mega Lounge', ['Dream Mega Lounge','Dream Mega Lounge (10 S. Calvert St.)']],
['Druid Hill Park', ['&nbsp;Druid Hill Park', 'Druid Hill Park', 'Druid Hill Park Pool']],
['Ekiben Hampden', ['Ekiben Hampden']],
['El Bufalo', ['El Bufalo']],
['Ema’s Corner', ['Ema’s Corner', 'Ema’s Corner (33 W North Ave)']],
['Emmanuel Episcopal Church', ['811 Cathedral St', 'Emmanuel Episcopal Church']],
['Enigma Bar', ['Enigma Bar']],
['Enoch Pratt Central Library', ['Enoch Pratt Central Library','Central Library (400 Cathedral St)', 'Enoch Pratt Central Library (400 Cathedral St)']],
['Eubie Blake Cultural Center', ['Eubie Blake Cultural Center','The Eubie (847 N. Howard)']],
['Euphoria', ['Euphoria']],
['Fadensonnen', ['<span style="color: #444444">Fadensonnen</span>', 'Faddensonnen', 'Fadensonnen', 'Fadensonnen   <br />', 'Fadensonnen (3 W 23rd St.)', 'Fadensonnen Beer Garden', 'Fadensonnen Upstairs Wine Bar', 'Fadensonnen Wine Bar', 'Fadensonnen Wine Bar Upstairs', 'Fadensonnen Winebar']],
['Fells Point', ['Fells Point', 'Fell’s Point']],
['Floristree', ['Floristree']],
['Flower Tower',['Flower Tower']],
['Fort Armistead',['Fort Armistead','Fort Armistead (DM bands for address)', 'Fort Harmistead (DM bands for address)']],
['Franklin Square Park', ['Franklin Square Park']],
['Frank’s Bay Tavern', ['Frank’s Bay Tavern']],
['Free Farm', ['&nbsp;Free Farm', 'Baltimore Free Farm', 'Free Farm', 'Free Farm (3511 Ash St)']],
['Freight Zone',['Freight Zone','Freight Zone (next to True Vine)']],
['Frog Shack',['Frog Shack','Frog Shack (DM @zd_rom_ for address)']],
['Function Coworking Community', ['Function Coworking Community']],
['George Peabody Library', ['George Peabody Library']],
['Get Shredded Vintage', ['Get Shredded Vintage']],
['Golden West', ['Golden West', 'Golden West Cafe']],
['Good Neighbor Design Garage', ['Good Neighbor Design Garage']],
['Goucher College', ['Goucher College','Goucher College (Heubeck Multipurpose Room)', 'Goucher College (Trustees Hall)', 'Goucher College Chapel', 'Goucher Glass Studio Trustees Hall']],
['Graffiti Warehouse', ['Graffiti Warehouse']],
['Grass Bmore', ['Grass Bmore','Grass Bmore (1100 Wilcomico St, Suite 350)', 'Wico St. Beer Company', 'Wico Street Beer Co.']],
['Greektown Square and Event Center', ['Greektown Square and Event Center','Greektown Square &amp; Event Center', 'Greektown square and event center']],
['Guilford Hall Brewery', ['1611 Guilford Ave', 'Guilford Hall Brewery']],
['HI Baltimore Hostel', ['HI Baltimore Hostel']],
['Hammerjacks', ['Hammerjacks']],
['Hampden', ['Hampden', 'The Ave in Hampden']],
['Hampden Park', ['Hampden Park','Hampden Park (Outdoors)', 'Roosevelt Park (36th St &amp; Falls Rd)']],
['Hampden Skate Park', ['Hampden Skate Park', 'Hampden Skatepark', 'Skate Park of Baltimore', 'Skatepark of Baltimore', 'Skatepark of Bmore']],
['Hard Rock Cafe', ['Hard Rock Cafe','Hard Rock Cafe (601 E Pratt St)']],
['Hargrove', ['Hargrove']],
['Haus',['Haus','Haus (DM wmbc_radio for address)']],
['Heinz Park', ['Heinz Park']],
['Herring Run', ['Herring Run', 'Herring Run Park']],
['Hidden Harvest', ['Hidden Harvest', 'Hidden Harvest Community Farm (1825 N Calvert St)']],
['Hippodrome', ['Hippodrome', 'Hippodrome&nbsp;', 'The Hippodrome']],
['Hollins Market', ['Hollins Market']],
['Holy Frijoles', ['Holy Frijoles', 'Holy Frijoles &nbsp;', 'Holy Frijoles Upstairs', 'Holy Frijoles</strike>', 'Holy Frjoles', 'Hoy Frijoles']],
['Homewood Friends Meeting House', ['Homewood Friends Meeting House', 'Homewood Friends Meeting House (3107 N. Charles St.)']],
['Hot Dog Central', ['Hot Dog Central']],
['Hot Rock Art Collective', ['Hot Rock Art Collective','Hot Rock Art Collective (3701 Parkside Dr.)']],
['House of Chiefs', ['Houde of Chiefs', 'House of Chiefs', 'House of Chiefs (4603 York Road)', 'House of Chiefs (4604 York Rd)']],
['House of Sedulo',['House of Sedulo']],
['House of Za',['House of Za','House of Za (DM bands for address)']],
['Idle Hour', ['Idle Hour','Idle Hour (201 E Fort Ave)']],
['Iiinteruption Studios',['Iiinteruption Studios']],
['Immaculate Heart of Mary Church', ['Immaculate Heart of Mary Church']],
['Inner Habor Amphitheater', ['Inner Habor Amphitheater', 'Inner Harbor Amphitheater']],
['Inner Harbor Wine Village', ['Inner Harbor Wine Village']],
['Jacksons House', ['Jacksons House','jackson_s_house (806 Berry St)']],
['James E Hooper House', ['James E Hooper House','James E Hooper House (100 east 23rd St)']],
['Jewish Museum of Maryland', ['Jewish Museum of Maryland']],
['Joe Squared', ['Ema’s Corner', 'Joe Squared', 'Joe Squared Upstairs', 'Joe Squared&nbsp;', 'Joe Squared&nbsp;Electric Feels. 9PM, $17 @ Rams Head', 'Joe SquaredSpite, Boundaries, Vatican, Bodybox, Delenda. 6PM, $19 @ Soundstage']],
['Joes Tavern', ['Joes Tavern','Joes Tavern (1006 Dundalk Ave)']],
['Johns Hopkins University', ['Johns Hopkins University','Johns Hopkins University (Shriver Hall Auditorium)']],
['Kenwood Tavern', ['Kenwood Tavern']],
['Keystone Korner', ['Keystone Korner']],
['Koopatini House',['Koopatini House','Koopatini Haus (DM bands for address)']],
['Ladew Topiary Gardens', ['Ladew Topiary Gardens']],
['Lake Montebello', ['Lake Montebello']],
['Lansdowne Skatepark', ['Lansdowne Skatepark', 'Sandy Hill Skatepark']],
['Laurens and Roberts St', ['Laurens and Roberts St','Laurens &amp; Roberts St']],
['Le Mondo', ['Le Mondo', 'Le Mondo (406 N Howard)']],
['Lewis Museum', ['Lewis Museum']],
['Lithuanian Hall', ['Lithuanian Hall','Lith Hall']],
['Little Havana', ['Little Havana']],
['Local Oyster (Locust Point)', ['Local Oyster (Locust Point)']],
['Lost and Found', ['Lost and Found','1601 Ridgely St','1601 Ridgely St.', 'Lost &amp; Found (1601 Ridgely St)', 'Lost &amp; Found (1601 Ridgely St.)']],
['Lovely Lane Church', ['Lovely Lane Church']],
['M&T Bank Exchange', ['M&T Bank Exchange','M&amp;T Bank Exchange']],
['Pier Six', ['MECU Pavilion', 'Pier Six', 'Pier Six Pavilion']],
['MICA Game Lab', ['MICA Game Lab','MICA Game Lab (100 Dolphin St)']],
['MICA Meyerhoff Gallery', ['MICA Meyerhoff Gallery']],
['Madison and Presstman St', ['Madison and Presstman St','Madison &amp; Presstman St']],
['Manor Mill', ['Manor Mill']],
['MAP Technologies', ['322 W Baltimore St.','322 W. Baltimore St.', 'M.A.P. Technologies', 'M.A.P. Technologies (322 W Baltimore St.)', 'MAP Technologies', 'Map Technologies (322 W. Baltimore St)', 'Map Technologies (322 W. Baltimore St.)', 'MapTech Games','M.A.P. Technologies (322 W. Baltimore St)']],
['Marikle Chapel', ['Marikle Chapel','Marikle Chapel (Notre Dame of Maryland University, Theresa Hall)']],
['Market Maven', ['Market Maven']],
['Maryland Science Center', ['Maryland Science Center']],
['Maximon', ['Maximon']],
['Mercury Theater', ['Mercury Theater', 'Mercury Theatre']],
['Metro Gallery', ['Metro', 'Metro Gallery', 'Metro GalleryB&bull;A&bull;D Night | Gunbuster. 6PM, $FREE @ Crown']],
['Mi Comalito', ['Mi Comalito', 'Mi Comalito (2101 N Charles St)']],
['Mice in the Attic',['Mice in the Attic','Mice In The Attic']],
['Micky’s Joint', ['Mickey’s Joint', 'Mickey’s Joint (5403 Harford Rd)', 'Micky’s Joint']],
['Middle Branch Park', ['3301 Waterview Ave', 'Middle Branch Park', 'Middle Branch Park (3301 Waterview Ave)']],
['Mindpub', ['Mindpub']],
['Ministry of Brewing', ['Ministry of Brewing']],
['Mobtown Brewing', ['Mobtown Brewing','Mobtown (4015 Foster Ave)', 'Mobtown Brewery', 'Mobtown Brewing Co.']],
['The Lyric', ['Modell Lyric', 'The Lyric', 'The Lyric</strike>', 'The Lyric<br>“Wrong Way” w/ MR Sauter &amp; Joanne McNeil. 7PM, $FREE @ Red Emma’s', 'The Modell Lyric']],
['Monument Brewing', ['Monument Brewing', 'Monument City Brewing', 'Monument City Brewing</strike>']],
['Morsbergers', ['Morsbergers', 'Morsberger’s', 'Morsebegers']],
['Mosaic', ['Mosaic', 'Power Plant', 'Power Plant Live', 'Powerplant', 'Powerplant Live']],
['Mothers Grille', ['Mothers Grille', 'Mother’s']],
['Motor House', ['Motor House', 'Motorhouse']],
['Mount Royal Soap Co.', ['Mount Royal Soap Co.', 'Mt. Royal Soaps']],
['Mt Vernon Marketplace', ['Mt Vernon Marketplace']],
['Mt Vernon Records', ['Mt Vernon Records']],
['Mt Vernon', ['Mt Vernon','Mt. Vernon']],
['Mulberry St and Park Ave', ['Mulberry St and Park Ave']],
['Mums', ['Mums']],
['National Aquarium', ['National Aquarium']],
['Night Owl Gallery', ['Night Owl Gallery']],
['No address listed',['No address listed','Address sent after ticket purchase on RA', 'Address shown after ticket purchase (zip 21210)','Location TBA','Online on Twitch','Purchase tickets for address']],
['No address listed, DM for address',['No address listed, DM for address','DM @andieisonline for tix/address','DM @beatitude.bmore for address','DM @sidebarbaltimore for address','DM Darkroom for address','DM Digital Xscape for address','DM Nothing Nice','DM Signal Route for address','DM artists for address','DM bands for address','DM beatitude.bmore for address','DM data_mine on Instagram for address','DM digitalxscape for address','DM everafter__party for address','DM inmysoulzine for address','DM itsjacqjill for address', 'Email hello@respektmusic.com','Call 877-577-BOOM or DM Crass Lips Records','Outside (DM bands for address)','Secret Location Downtown Baltimore (DM On Point Events for info)','House show (DM bands for address)','Charles Village (message bands for address)','Station North (DM bands for address)']],
['No Land Beyond', ['No Land Beyond', 'No Land Beyond, 2125 Maryland Ave (new location)']],
['Nobles Bar and Grill', ['Nobles Bar and Grill','Nobles Bar &amp; Grill']],
['NoMuNoMu', ['NoMuNoMu','709 Howard St', '709 N. Howard St', '709 N. Howard St.', 'NoMu NoMu', 'NoMu NoMu (709 N. Howard St)', 'NoMüNoMü']],
['Normal’s Books', ['Normal&rsquo;s Books', 'Normals', 'Normals Books', 'Normal’s', 'Normal’s Books', 'Red Room']],
['North Ave', ['North Ave', 'North Ave &amp; Charles St', 'Station North']],
['North Charles and 33rd St', ['North Charles and 33rd St','Route begins at North Charles and 33rd St.']],
['Of Love And Regret', ['Of Love And Regret']],
['Old Line Spirits', ['Old Line Spirits']],
['Old Major', ['Old Major', 'Old Major (900 S. Carey St.)']],
['Old York Lot',['Old York Lot','Old York Lot (outdoors - message bands for address)']],
['Oliver Brewing Company', ['Oliver Brewing Company', 'Oliver Brewing Company (Outside)']],
['Onle Vibez', ['Onle Vibez','Onle Vibez (3241 Belar Rd)']],
['Orion Studios', ['Orion Studios']],
['Ottobar', ['&nbsp;Ottobar', 'OttobaR', 'Ottobar', 'Ottobar Patio', 'Ottobar Upstairs', 'Ottobar Upstairs<br>Metroschock. 9PM, $10 @ Metro Gallery', 'Ottobar&nbsp;', 'OttobarCell, Myopic, Skaldr, Egalabalus. @ Sidebar', 'The Ottobar']],
['P.A.L.M.', ['P.A.L.M.','25 E. Cross St', 'Locals Only', 'P.A.L.M. (25 E Cross St)', 'P.A.L.M. (25 E. Cross St)', 'Palm (25 E. Cross St.)']],
['Pariah Brewing', ['Pariah Brewing', 'Pariah Brewing Company']],
['Parkway Theatre', ['Parkway Theatre', 'Parkway Theatre + MICA']],
['Parris Underground', ['Parris Underground','Parris Underground (497 Ritchie Highway Suite C)']],
['Patriot Plaza', ['Patriot Plaza']],
['Patterson Park', ['Patteron Park Pagoda', 'Patterson Park', 'Patterson Park (2800 Eastern &amp; Linwood Aves)', 'Patterson Park (northwest corner)', 'Patterson Park Observatory', 'Patterson Park Pagoda', 'Patterson Park Pagoda Observatory', 'Patterson Park Pulaski Monument']],
['Peabody Heights Brewery', ['Barclay &amp; 30th St + Peabody Heights Brewery', 'Peabody Brewing', 'Peabody Height Brewery', 'Peabody Heights', 'Peabody Heights Brewery', 'Peabody Heights Brewery</strike>', 'Peabody Heights Brewing']],
['Peabody Maestro’s Cafe', ['Peabody Maestro’s Cafe']],
['Pearlstone Park', ['Pearlstone Park']],
['Penn and Baker St', ['Penn and Baker St','Penn &amp; Baker St.']],
['Phlote', ['Phlote','300 W Pratt St','300 W. Pratt St.', '300 West Pratt St', 'Phlote (300 W Pratt St 3rd floor)', 'Phlote (300 W Pratt St)', 'The Office (300 W. Pratt St)']],
['Phoenix Art Yard (1320 Bayard St)', ['Phoenix Art Yard (1320 Bayard St)']],
['Phoenix Cultural', ['Phoenix Cultural']],
['Pink Lounge',['Pink Lounge']],
['Pique Collective',['Pique Collective']],
['Pitango Bakery &amp; Cafe', ['Pigtango Bakery &amp; Cafe', 'Pitango Bakery &amp; Cafe']],
['Polish Home Club', ['Polish Home Club']],
['Port Covington', ['Port Covington']],
['PP Palace',['PP Palace','PP Palace (DM bands for address)']],
['Pratt St and Ellwood Ave', ['Pratt St and Ellwood Ave','Pratt St &amp; Ellwood Ave']],
['Purr Palace',['Purr Palace','Purr Palace (DM bands for address)']],
['Pussy Palace',['Pussy Palace','Pussy Palace (DM bands for address)']],
['R House', ['R House','R House Garage &amp; Patio', 'R. House Garage']],
['Racers Cafe (7732 Harford Rd - outside)', ['Racers Cafe (7732 Harford Rd - outside)']],
['Rams Head', ['Rams Head', 'Rams Head Live', 'Rams Head<br>Usher. 8PM, $260 @ CFG Arena']],
['Raw and Refined', ['Raw and Refined','Raw &amp; Refined', 'Raw &amp; Refined (2723 Lighthouse Point)']],
['Recher', ['Recher', 'The Recher']],
['Red Emma’s', ['Red Emma&rsquo;s', 'Red Emma’s']],
['Remington Ave', ['Remington Ave', 'Remington Ave (Remington Ave &amp; 28th St)']],
['Remington Ave and 28th St', ['Remington Ave and 28th St','Remington Ave &amp; 28th St']],
['Renaissance Harborplace Hotel', ['Renaissance Harborplace Hotel']],
['Reverb', ['Reverb']],
['Rituals', ['RItuals', 'Rituals']],
['Robert and Bolton St', ['Robert and Bolton St','Robert &amp; Bolton St']],
['Robert C. Marshall Park', ['Robert C. Marshall Park']],
['Rocket to Venus', ['Rocket To Venus', 'Rocket To Venus  <br />', 'Rocket to Venus']],
['Roland Park Community Center', ['Roland Park Community Center']],
['Roland Water Tower', ['Roland Water Tower','Roland Water Tower (4210 Roland Ave)','&nbsp;Roland Water Tower (4210 Roland Ave)', 'Roland Water Tower']],
['Royal Blue', ['Royal Blue', 'Royal Blue  <br />', 'The Royal Blue']],
['Royal Rumble',['Royal Rumble']],
['Rumble Room',['Rumble Room','Rumble Room (DM artists for address)']],
['Secret Beach',['Secret Beach', 'Secret Beach (DM bands for address)']],
['Shake and Bake', ['Shake and Bake','Shake &amp; Bake', 'Shake &amp; Bake Family Fun Center', 'Shake n’ Bake', "Shake'n'Bake Family Fun Center"]],
['Shamrock Inn', ['Shamrock Inn', 'The Shamrock Inn']],
['Sicilys', ['Sicilys']],
['Sidebar', ['Sidebar', 'Sidebar</a>']],
['Sidedoor',['Sidedoor','Side Door (DM bands for address)', 'Sidedoor   (DM SidedoorsBaltimore for addy)', 'Sidedoor (DM SidedoorsBaltimore for addy)', 'Sidedoor (DM bands for address)']],
['Sisson Street Community Park', ['2701 Sisson St', 'SIsson St Community Park', 'Sisson Street Community Park']],
['Sky Tower',['Sky Tower','Sky Tower (DM bands for address)']],
['Snack Castle Castle',['Snack Castle Castle','Snack Castle Castle (DM bands for address)']],
['Sound Garden', ['Sound Garden','1616 Thames St', 'Baby’s On Fire (Fells Point)', 'Baby’s on Fire (Fells Point)', 'Baby’s on Fire - Fells Point', 'Luna Garden (1616 Thames St)', 'Sound Garden', 'Soundgarden Records', 'The Sound Garden']],
['Southpaw', ['Southpaw','Southpaw (529 S Bond St)']],
['Southwest Corner of Patterson Park', ['Southwest Corner of Patterson Park']],
['Space 4321', ['Space 4321','Space 4321 (4321 Harford Rd)']],
['Spirits of Mt Vernon', ['Spirits of Mt Vernon']],
['Squeak',['Squeak','Squeak (call 877-577-BOOM for address)']],
['St Mary’s Park', ['St Mary’s Park', 'St. Mary’s Park']],
['St Mary’s Restaurant', ['St Mary’s Restaurant','St Mary’s Restaurant (120 W 25th St)', 'St. Mary’s Upstairs (120 W. 25th St)']],
['St Nicholas Church', ['St Nicholas Church']],
['St David’s Episcopal Church', ['St David’s Episcopal Church','St. David’s Episcopal Church (4700 Roland Ave)', 'St. David’s Episcopal Church of Roland Park']],
['St Luke’s Church', ['St Luke’s Church','St. Luke’s Church', 'St. Luke’s Church (800 W 36th St)']],
['Stem and Vine', ['Stem and Vine','Stem &amp; Vine']],
['Stevenson Ranch',['Stevenson Ranch']],
['Stoneleigh Lanes', ['Stoneleigh Lanes']],
['Studio 10', ['Studio 10', 'Studio Ten 10']],
['Submersive HQ', ['Submersive HQ','Submersive HQ (3523 Buena Vista Ave)']],
['Sweet 27', ['Sweet 27']],
['Tacos Tijuana', ['Tacos Tijuana','Tacos Tijuana (1709 Edgewood Rd)']],
['Tarantula Hill', ['Tarantula Hill']],
['Terra Cafe', ['Terra Cafe','Terra Cafe (outdoors)']],
['The Biddle', ['The Biddle','The Biddle (1 W Biddle St)']],
['The Bun Shop', ['The Bun Shop']],
['The Calbox',['The Calbox','The Calbox (DM bands for address)']],
['The Can Company', ['The Can Company']],
['The Carroll Mansion', ['The Carroll Mansion']],
['The Castle',['The Castle','The Castle (DM bands for address)']],
['The Cat’s House',['The Cat’s House','The Cat’s House (DM bands for address)']],
['The Cave',['The Cave','The Cave (DM bands for address)']],
['The Cigarette Jar',['The Cigarette Jar','The Cigarette Jar (DM bands for address)']],
['The Compound', ['The Compound', 'The Compound (2239 Kirk Ave)', 'The Compound (DM bands for address)', 'The Compound&nbsp;  (2239 Kirk Ave)']],
['The Copycat', ['The Copycat','The Copycat (6th floor)']],
['The Deport', ['The Deport', 'The Depot']],
['The Empanada Lady', ['The Empanada Lady']],
['The Forest',['The Forest','The Forest (DM ___by_my_reanimated_corpse for address)', 'The Forest (DM bands for address)', 'The Forest (DM bmorezinefest for address)']],
['The Fort',['The Fort','The Fort (DM bands for address)']],
['The Hargrove', ['The Hargrove','The Hargrove (2223 Hargrove St)','The Hargrove (DM artists for address)','2225 Hargrove St', 'The Hargrove', 'The Hargrove (2225 Hargrove Aly)']],
['The Hole',['The Hole','The H.O.L.E. (DM bmorezinefest for address)', 'The Hole (DM bands below for address)', 'The Hole (DM bands for address)', 'The Hole (DM bmorezinefest for address)', 'The Hole Severna Park (DM bands for address)']],
['The Jaded Lounge',['The Jaded Lounge']],
['The Manor', ['The Manor']],
['The Parlor (108 W. North Ave.)', ['The Parlor (108 W. North Ave.)']],
['The Parlor (803 St. Paul)', ['The Parlor (803 St. Paul)']],
['The Peale', ['225 Holliday St', 'The Peale']],
['The Pearl Gallery', ['The Pearl Gallery']],
['The Point', ['The Point']],
['The Reservoir', ['The Reservoir']],
['The Rockwell', ['The Rockwell']],
['The Ruins',['The Ruins','The Ruins (DM bands for address)', 'The Ruins (DM nfc.underground for address)']],
['The Skatepark',['The Skatepark','The Skatepark (DM bands for address)']],
['The Undercroft', ['The Undercroft', 'Undercroft', 'Undercroft (outdoors)']],
['The Vortex', ['The Vortex','202 Ingleside Ave', 'The Vortex (CAA Park)', 'The Vortex CAA Park', 'The Vortex at CAA Park']],
['The Voxel', ['The Voxel', 'The Voxel (9 W 25th St) [FREE stream: <a href="http://twitch.tv/mofbaltimore">twitch.tv/mofbaltimore</a>]', 'The Voxel (9 W 25th St) [FREE stream:&nbsp;<a href="http://twitch.tv/mofbaltimore">twitch.tv/mofbaltimore</a>]']],
['The Wiggle Room', ['The Wiggle Room','3000 Falls Rd', 'The Wiggle Room (3000 Falls Rd)', 'Wiggle Room (3000 Falls Rd)', 'Wiggle Room (DM bands for address)']],
['The Wine Collective', ['The Wine Collective', 'Wine Collective']],
['Thee Portal',['Thee Portal', 'Thee Portal (DM artists for address)', 'Thee Portal (DM bands for address)', 'Thee Portal (DM for address)']],
['Trophy House',['Trophy House','Trophy House/4 q u a r i u m (email suzannedoogan at gmail dot com for address)']],
['UC Ballroom',['UC Ballroom']],
['Warehouse',['Warehouse','Warehouse (DM @theeronwesley for address)', 'Warehouse (DM for address)', 'Warehouse (tix on Resident Advisor)']],
['Waverly Commons', ['Waverly Commons','The Waverly Commons', 'Waverly Commons (32nd St &amp; Brentwood Ave)', 'Waverly Commons (418 E 32nd St)']],
['The Wren', ['The Wren']],
['Topside', ['Topside']],
['Towson Planetarium', ['Towson Planetarium']],
['True Vine', ['True Vine', 'True Vine Record Shop', 'True Vine Records']],
['Union Square Park', ['Union Square Park', 'Union Square Park (31 S. Gilmor St)']],
['University of Baltimore Student Center Auditorium', ['University of Baltimore Student Center Auditorium','21 W. Mt Royal 5th Floor', 'University of Baltimore (Wright Theater)', 'University of Baltimore Student Center Auditorium 5th floor (SE Corner Mt Royal &amp; Maryland)','Wright Theater (University of Baltimore)']],
['Uranus',['Uranus','Uranus (DM bands for address)']],
['Village Learning Place', ['Village Learning Place','Village Learning Place (2521 St. Paul St)']],
['Wax Atlas', ['Wax Atlas','WAX ATLAS (22 W 25th St.)']],
['War Memorial Plaza', ['War Memorial Plaza','War Memorial Plaza (101 N. Gay St)']],
['Warehouse Cinema', ['Warehouse Cinema', 'Warehouse Cinema Rotunda', 'Warehouse Cinemas']],
['Watermelon Room',['Watermelon Room','Watermelon Room (DM bands for address)', 'Watermelon Room (DM bands for tix+address)','The Watermelon Room (DM bands for address)']],
['Waverly Brewery Company', ['Waverly Brewery Company', 'Waverly Brewing', 'Waverly Brewing Co.', 'Waverly Brewing Company', 'Waverly Craft Brewing']],
['Waverly Main St', ['Waverly Main St']],
['Waverly United Methodist', ['Waverly United Methodist']],
['Wax Atlas', ['Wax Atlas', 'Wax Atlas Records']],
['Weiss Imports and Domestics', ['Weiss Imports and Domestics','Weiss Imports &amp; Domestics (1160 Homestead St)']],
['Whitelock Community Farm', ['Whitelock Community Farm','Whitelock Community Farm (930 Whitelock St. 21217)']],
['Wxterhouse Studio', ['Wxterhouse Studio','Wxterhouse Studio (2202 Boston St)']],
['Wyman Park Dell', ['Wyman Park', 'Wyman Park Dell']],
['Wyman Park Baseball Diamond', ['Wyman Park Baseball Diamond','Wyman Park Baseball Diamond (West 37th &amp; Beech Ave)']],
['Ye Olde Emerald Tavern', ['Ye Olde Emerald Tavern']],
['YNOT Lot', ['Starts at YNOT Lot', 'YNOT LOT', 'YNOT Lot', 'Ynot Lot', 'Ynot Lot (4PM)/True Vine (3PM)']],
['York Rd and Woodbourne Ave', ['York Rd and Woodbourne Ave','York Rd &amp; Woodbourne Ave']],
['Zen West', ['Zen West']],
['Zoo Pavillion', ['Zoo Pavillion','Zoo Pavillion (1 Safari Place)']],

['Zika Farm', ['Zika Farm', 'Zika Farm (Address shown w/ ticket purchase)', 'Zika Farm (DM artists for address)', 'Zika Farm (DM bands for address)', 'Zika Farm (DM data_mine for address)', 'Zika Farm (use QR code on flyer for location)']],
['Zion Lutheran Church', ['Zion Lutheran Church', 'Zion Lutheran Church (400 E Lexington St)']],
['Zissimos', ['The Lou Costello Room Comedy Club', 'Zissimos', 'Zissimos Bar', 'Zissimos</strike>', 'Zissimo’s']]
]


#for thisvenue in list_of_venues:
#  canonical = thisvenue[0]
#  alias_list = thisvenue[1]
#  if canonical in alias_list:
#    pass
#  else:
#    print(canonical)

all_venue_list = []

for thisvenue in list_of_venues:
  canonical = thisvenue[0]
  alias_list = thisvenue[1]
  for thisalias in alias_list:
    thismapping = [thisalias,canonical]
    all_venue_list.append(thismapping)

all_venue_list.sort()

#for thisvenue in all_venue_list:
#  print(thisvenue)

#print(all_venue_list)

print('all_venue_dict = {')
for thismapping in all_venue_list:
  print("  '" + thismapping[0] + "':'" + thismapping[1] + "',")
print('}')
